# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='top_name',
            new_name='topic_name',
        ),
    ]
